// Generated by scripts/build-tracks.mjs. Do not edit.
import type { TrackCoverage, TrackData } from './types';
import { baku } from './data/baku';
import { sepang } from './data/sepang';
import { marinaBay } from './data/marina-bay';
import { cota } from './data/cota';
import { hermanosRodriguez } from './data/hermanos-rodriguez';
import { interlagos } from './data/interlagos';
import { lasVegas } from './data/las-vegas';
import { lusail } from './data/lusail';
import { yasMarina } from './data/yas-marina';
import { sakhir } from './data/sakhir';
import { jeddah } from './data/jeddah';
import { albertPark } from './data/albert-park';
import { suzuka } from './data/suzuka';
import { shanghai } from './data/shanghai';
import { miami } from './data/miami';
import { gillesVilleneuve } from './data/gilles-villeneuve';
import { monaco } from './data/monaco';
import { portimao } from './data/portimao';
import { silverstone } from './data/silverstone';
import { redBullRing } from './data/red-bull-ring';
import { spa } from './data/spa';
import { hungaroring } from './data/hungaroring';
import { monza } from './data/monza';
import { madring } from './data/madring';
import { istanbulPark } from './data/istanbul-park';

export type { TrackCoverage, TrackData } from './types';

export const TRACKS_BY_CIRCUIT: Record<string, TrackData> = {
  "baku": baku,
  "sepang": sepang,
  "marina-bay": marinaBay,
  "cota": cota,
  "hermanos-rodriguez": hermanosRodriguez,
  "interlagos": interlagos,
  "las-vegas": lasVegas,
  "lusail": lusail,
  "yas-marina": yasMarina,
  "sakhir": sakhir,
  "jeddah": jeddah,
  "albert-park": albertPark,
  "suzuka": suzuka,
  "shanghai": shanghai,
  "miami": miami,
  "gilles-villeneuve": gillesVilleneuve,
  "monaco": monaco,
  "portimao": portimao,
  "silverstone": silverstone,
  "red-bull-ring": redBullRing,
  "spa": spa,
  "hungaroring": hungaroring,
  "monza": monza,
  "madring": madring,
  "istanbul-park": istanbulPark,
};

/** Race id -> circuit id (venues verified; see scripts/data/SOURCES.md). */
export const CIRCUIT_BY_RACE: Record<string, string> = {
  "2026-r15-azerbaijan": "baku",
  "2026-r16-malaysia": "sepang",
  "2026-r17-singapore": "marina-bay",
  "2026-r18-united-states": "cota",
  "2026-r19-mexico": "hermanos-rodriguez",
  "2026-r20-brazil": "interlagos",
  "2026-r21-las-vegas": "las-vegas",
  "2026-r22-qatar": "lusail",
  "2026-r23-abu-dhabi": "yas-marina",
  "2027-r1-bahrain": "sakhir",
  "2027-r2-saudi-arabia": "jeddah",
  "2027-r3-australia": "albert-park",
  "2027-r4-japan": "suzuka",
  "2027-r5-china": "shanghai",
  "2027-r6-miami": "miami",
  "2027-r7-canada": "gilles-villeneuve",
  "2027-r8-monaco": "monaco",
  "2027-r9-portugal": "portimao",
  "2027-r10-great-britain": "silverstone",
  "2027-r11-austria": "red-bull-ring",
  "2027-r12-belgium": "spa",
  "2027-r13-hungary": "hungaroring",
  "2027-r14-italy": "monza",
  "2027-r15-spain": "madring",
  "2027-r16-azerbaijan": "baku",
  "2027-r17-turkiye": "istanbul-park",
  "2027-r18-singapore": "marina-bay",
  "2027-r19-united-states": "cota",
  "2027-r20-mexico": "hermanos-rodriguez",
  "2027-r21-brazil": "interlagos",
  "2027-r22-las-vegas": "las-vegas",
  "2027-r23-qatar": "lusail",
  "2027-r24-abu-dhabi": "yas-marina",
};

export const TRACK_COVERAGE: TrackCoverage[] = [
  { raceId: "2026-r15-azerbaijan", circuitId: "baku", status: 'available' },
  { raceId: "2026-r16-malaysia", circuitId: "sepang", status: 'available' },
  { raceId: "2026-r17-singapore", circuitId: "marina-bay", status: 'available' },
  { raceId: "2026-r18-united-states", circuitId: "cota", status: 'available' },
  { raceId: "2026-r19-mexico", circuitId: "hermanos-rodriguez", status: 'available' },
  { raceId: "2026-r20-brazil", circuitId: "interlagos", status: 'available' },
  { raceId: "2026-r21-las-vegas", circuitId: "las-vegas", status: 'available' },
  { raceId: "2026-r22-qatar", circuitId: "lusail", status: 'available' },
  { raceId: "2026-r23-abu-dhabi", circuitId: "yas-marina", status: 'available' },
  { raceId: "2027-r1-bahrain", circuitId: "sakhir", status: 'available' },
  { raceId: "2027-r2-saudi-arabia", circuitId: "jeddah", status: 'available' },
  { raceId: "2027-r3-australia", circuitId: "albert-park", status: 'available' },
  { raceId: "2027-r4-japan", circuitId: "suzuka", status: 'available' },
  { raceId: "2027-r5-china", circuitId: "shanghai", status: 'available' },
  { raceId: "2027-r6-miami", circuitId: "miami", status: 'available' },
  { raceId: "2027-r7-canada", circuitId: "gilles-villeneuve", status: 'available' },
  { raceId: "2027-r8-monaco", circuitId: "monaco", status: 'available' },
  { raceId: "2027-r9-portugal", circuitId: "portimao", status: 'available' },
  { raceId: "2027-r10-great-britain", circuitId: "silverstone", status: 'available' },
  { raceId: "2027-r11-austria", circuitId: "red-bull-ring", status: 'available' },
  { raceId: "2027-r12-belgium", circuitId: "spa", status: 'available' },
  { raceId: "2027-r13-hungary", circuitId: "hungaroring", status: 'available' },
  { raceId: "2027-r14-italy", circuitId: "monza", status: 'available' },
  { raceId: "2027-r15-spain", circuitId: "madring", status: 'available' },
  { raceId: "2027-r16-azerbaijan", circuitId: "baku", status: 'available' },
  { raceId: "2027-r17-turkiye", circuitId: "istanbul-park", status: 'available' },
  { raceId: "2027-r18-singapore", circuitId: "marina-bay", status: 'available' },
  { raceId: "2027-r19-united-states", circuitId: "cota", status: 'available' },
  { raceId: "2027-r20-mexico", circuitId: "hermanos-rodriguez", status: 'available' },
  { raceId: "2027-r21-brazil", circuitId: "interlagos", status: 'available' },
  { raceId: "2027-r22-las-vegas", circuitId: "las-vegas", status: 'available' },
  { raceId: "2027-r23-qatar", circuitId: "lusail", status: 'available' },
  { raceId: "2027-r24-abu-dhabi", circuitId: "yas-marina", status: 'available' },
];

export function trackForRace(raceId: string): TrackData | null {
  const circuit = CIRCUIT_BY_RACE[raceId];
  return circuit ? (TRACKS_BY_CIRCUIT[circuit] ?? null) : null;
}
